### ISSUE TITLE
Water Set Temperature

### ISSUE THREAD

**Issue by benlbrm** [benlbrm/hottohpy#4]
Hello @elkarto, 
In version 0.0.27, I've expose a function set_water_temperature that is setting an not documented register, can you give a try ?
You can also try with constant form 12 to ??

`    
def set_water_temperature(self, value):
    """Set Target Water Temperature of the stove"""
    try:
            result = self.client.sendCommand(
                parameters=[
                    str(StoveCommands.INCONNU_4.value),
                    str(value * 10),
                ]
            )
            return result
        except:
            raise
`

**Comment by elkarto** [comment]
It doesn't appear to be working.

I have not found any stove parameter that changes its value when I run this function with any data.

**Comment by benlbrm** [comment]
Ok thanks for your feedback. I could be logic than this is not a parameter than can be set, like for a boiler, for sanitary reasons.

**Comment by elkarto** [comment]
It's possible to set it from the stove panel. But it is probably not
possible from the wifi module.

**Comment by benlbrm** [comment]
Ah ok, like in my case for the fan1, I can set it from the panel but not form the wifi module...
