### ISSUE TITLE
Utilisation dans Node-Red

### ISSUE THREAD

**Issue by nomaro** [benlbrm/hottohpy#5]
Bonjour Benoit,
J'essaye d'utiliser ta librairie directement dans Node-Red (que j'utilise pour étendre les possibilités d'un système Loxone). Pourrais tu m'aider à implanter cela car j'avoue être un peu dépassé par le python. ^^'

**Comment by nomaro** [comment]
J'ai réussi en faisant un script pour chaque commande que je voulais utiliser comme ça la prog était assez basique pour moi :)

Sur Node-Red j'utilise la fonction EXEC avec la commande : "cd /home/pi/hottohpy ; python3 on.py"

Voici mon Flow Node-Red :
```
[{"id":"56d13d60.147ac4","type":"tab","label":"Flow 1","disabled":false,"info":""},{"id":"8875cff0.debc","type":"inject","z":"56d13d60.147ac4","name":"","props":[{"p":"payload","v":"","vt":"date"},{"p":"topic","v":"","vt":"string"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"","payloadType":"date","x":260,"y":160,"wires":[["5274ed1a.4e6c94"]]},{"id":"5274ed1a.4e6c94","type":"exec","z":"56d13d60.147ac4","command":"cd /home/pi/hottohpy ; python3 on.py","addpay":true,"append":"","useSpawn":"false","timer":"","oldrc":false,"name":"ON","x":410,"y":160,"wires":[["5fd0450c.42459c"],[],[]]},{"id":"5fd0450c.42459c","type":"debug","z":"56d13d60.147ac4","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","statusVal":"","statusType":"auto","x":590,"y":140,"wires":[]}]
``` 

Voici mon fichier on.py :

```python
# importing module
import sys

# appending a path
sys.path.append('src')
from hottohpy import Hottoh
import time

stove = Hottoh('192.168.XXX.XXX' ,5001, "lib")

stove.connect()

attempt = 1

while True:
        time.sleep(1)
        stove.set_on()
        print("POWER ON")
        time.sleep(1)
        stove.get_action()
        sys.exit()
``` 

Par contre, comme tu le vois sur mon script, je ne sais pas si c'est normal mais j'ai rencontré 2 petits problèmes : 
- je suis obliger d'attendre 1 sec, sinon la commande ne passe pas (ça me retourne non connecté) 
- je dois remettre une pause puis relancer une commande pour que mon set_on() soit prit en compte par le poele. Ca me fait ça sur toutes les commandes set_

**Comment by nomaro** [comment]
Au passage, j'utilise sur un poêle MCZ Vivo90 et ça fonctionne au poil👍 
Merci pour ton travail

**Comment by benlbrm** [comment]
Salut,Je viens de voir ton issue. Super si tu a reussi à t’en sortir ! Pour le délais d’une seconde entre deux commandes il le semble avoir eu le même phénomène lors de mes essais…Le 9 nov. 2023 à 19:11, nomaro ***@***.***> a écrit :﻿
Au passage, j'utilise sur un poêle MCZ Vivo90 et ça fonctionne au poil👍
Merci pour ton travail

**Comment by FranzKillig** [comment]
Bonjour à tous,

J'utilise également un MCZ Vivo90 et je souhaite le contrôler avec iobroker. Au cours de mes recherches, je suis tombé sur cette page. Je serais ravi si quelqu'un pouvait prendre le temps de répondre aux questions suivantes :

1. Comment établissez-vous la connexion avec la carte mère Hottoh ? Utilisez-vous l'adaptateur WiFi d'origine ou un convertisseur Modbus IP/RS232 ?

2. Si la communication avec Node-Red fonctionne, quelqu'un pourrait-il me fournir un flow complet ?

3. Où avez-vous obtenu les API nécessaires ?

Merci beaucoup pour votre soutien et désolé pour mon mauvais français. Comme je ne parle pas beaucoup français, je dois traduire les textes de l'allemand avec ChatGPT.

Cordialement,
Franz
